export const boundaryConfig = {
  topology: "monorepo",
  repositoryRole: "mixed",
  productionFiles: [
    "apps/*/src/**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}",
    "packages/*/src/**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}",
  ],
  testFilePatterns: [
    "**/*.{test,spec}.{js,cjs,mjs,jsx,ts,cts,mts,tsx}",
  ],
  testAllowedExternalDependencies: [],
  testAllowedCoreDependencies: [
    "node:assert/strict",
    "node:child_process",
    "node:crypto",
    "node:fs/promises",
    "node:os",
    "node:path",
    "node:util",
  ],
  workspaces: {
    "maintainer-api": {
      architectureRole: "application-shell",
      isDeploymentUnit: true,
      path: "apps/maintainer-api",
      packageName: "@patch-pilot/maintainer-api",
      sourceRoot: "src",
      allowedWorkspaceDependencies: ["maintenance"],
      modules: {
        application: {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "github-ingestion": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:buffer", "node:crypto"],
        },
        "run-timeline-feed": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "run-timeline-http": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["run-timeline-feed"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:url"],
        },
      },
      compositionFiles: {
        "index.js": {
          allowedModuleDependencies: [
            "application",
            "github-ingestion",
            "run-timeline-feed",
            "run-timeline-http",
          ],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "main.js": {
          allowedModuleDependencies: ["application"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
      },
    },
    "maintainer-worker": {
      architectureRole: "application-shell",
      isDeploymentUnit: true,
      path: "apps/maintainer-worker",
      packageName: "@patch-pilot/maintainer-worker",
      sourceRoot: "src",
      allowedWorkspaceDependencies: ["maintenance"],
      modules: {
        application: {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "docker-cli": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:child_process"],
        },
        "sandbox-execution": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["docker-cli"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:crypto"],
        },
      },
      compositionFiles: {
        "index.js": {
          allowedModuleDependencies: ["application", "docker-cli", "sandbox-execution"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "main.js": {
          allowedModuleDependencies: ["application"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
      },
    },
    "maintainer-web": {
      architectureRole: "application-shell",
      isDeploymentUnit: true,
      path: "apps/maintainer-web",
      packageName: "@patch-pilot/maintainer-web",
      sourceRoot: "src",
      allowedWorkspaceDependencies: [],
      modules: {
        application: {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
      },
      compositionFiles: {
        "index.js": {
          allowedModuleDependencies: ["application"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "main.js": {
          allowedModuleDependencies: ["application"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
      },
    },
    maintenance: {
      architectureRole: "conceptual-package",
      isDeploymentUnit: false,
      path: "packages/maintenance",
      packageName: "@patch-pilot/maintenance",
      sourceRoot: "src",
      allowedWorkspaceDependencies: [],
      modules: {
        "change-proposals": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: ["safety"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:path"],
        },
        critiques: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "proposal-attempts": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: ["critiques", "verifications"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        runs: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "repository-workspaces": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [
            "node:child_process",
            "node:fs/promises",
            "node:path",
            "node:process",
            "node:url",
            "node:util",
          ],
        },
        "repository-understanding": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:fs/promises", "node:path"],
        },
        reproductions: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "run-timelines": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: ["pg", "redis"],
          allowedCoreDependencies: [],
        },
        safety: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:path"],
        },
        verifications: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
      },
      compositionFiles: {
        "index.js": {
          allowedModuleDependencies: [
            "change-proposals",
            "critiques",
            "proposal-attempts",
            "repository-understanding",
            "repository-workspaces",
            "reproductions",
            "runs",
            "run-timelines",
            "safety",
            "verifications",
          ],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
      },
    },
  },
};
