export const boundaryConfig = {
  topology: "monorepo",
  repositoryRole: "mixed",
  productionFiles: [
    "apps/*/src/**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}",
    "packages/*/src/**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}",
  ],
  testFilePatterns: [
    "**/*.{test,spec}.{js,cjs,mjs,jsx,ts,cts,mts,tsx}",
  ],
  testAllowedExternalDependencies: [],
  testAllowedCoreDependencies: [
    "node:assert/strict",
    "node:buffer",
    "node:child_process",
    "node:crypto",
    "node:fs/promises",
    "node:http",
    "node:os",
    "node:path",
    "node:util",
  ],
  workspaces: {
    "maintainer-api": {
      architectureRole: "application-shell",
      isDeploymentUnit: true,
      path: "apps/maintainer-api",
      packageName: "@patch-pilot/maintainer-api",
      sourceRoot: "src",
      allowedWorkspaceDependencies: ["maintenance"],
      modules: {
        "api-authentication": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:crypto"],
        },
        "api-http": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["github-ingestion", "run-approval-http", "run-review-evidence-http", "run-timeline-http"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "api-server": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["api-http"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:buffer", "node:http", "node:timers", "node:url"],
        },
        application: {
          architectureRole: "application-role",
          allowedModuleDependencies: ["api-authentication", "api-server", "github-delivery", "github-ingestion", "run-review-query", "workflow-submission"],
          allowedExternalDependencies: ["pg"],
          allowedCoreDependencies: [],
        },
        "github-ingestion": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:buffer", "node:crypto", "node:url"],
        },
        "github-delivery": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "run-timeline-feed": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "run-approval-http": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:url"],
        },
        "run-review-evidence-http": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:url"],
        },
        "run-review-query": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "run-timeline-http": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["run-timeline-feed"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:url"],
        },
        "workflow-submission": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: ["@temporalio/client"],
          allowedCoreDependencies: [],
        },
      },
      compositionFiles: {
        "index.js": {
          allowedModuleDependencies: [
            "api-authentication",
            "api-http",
            "api-server",
            "application",
            "github-delivery",
            "github-ingestion",
            "run-approval-http",
            "run-review-evidence-http",
            "run-review-query",
            "run-timeline-feed",
            "run-timeline-http",
            "workflow-submission",
          ],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "main.js": {
          allowedModuleDependencies: ["application"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:process"],
        },
      },
    },
    "maintainer-worker": {
      architectureRole: "application-shell",
      isDeploymentUnit: true,
      path: "apps/maintainer-worker",
      packageName: "@patch-pilot/maintainer-worker",
      sourceRoot: "src",
      allowedWorkspaceDependencies: ["maintenance"],
      modules: {
        application: {
          architectureRole: "application-role",
          allowedModuleDependencies: ["maintenance-workflow", "proposal-generation"],
          allowedExternalDependencies: ["@temporalio/worker"],
          allowedCoreDependencies: ["node:url"],
        },
        "docker-cli": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:child_process"],
        },
        "sandbox-execution": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["docker-cli"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:crypto"],
        },
        "maintenance-workflow": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["sandbox-execution"],
          allowedExternalDependencies: ["@temporalio/workflow"],
          allowedCoreDependencies: [],
        },
        "proposal-generation": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:buffer"],
        },
      },
      compositionFiles: {
        "index.js": {
          allowedModuleDependencies: ["application", "docker-cli", "maintenance-workflow", "proposal-generation", "sandbox-execution"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "main.js": {
          allowedModuleDependencies: ["application"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:process"],
        },
      },
    },
    "maintainer-web": {
      architectureRole: "application-shell",
      isDeploymentUnit: true,
      path: "apps/maintainer-web",
      packageName: "@patch-pilot/maintainer-web",
      sourceRoot: "src",
      allowedWorkspaceDependencies: [],
      modules: {
        application: {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "run-review": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "run-review-api": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:buffer", "node:http", "node:https", "node:url"],
        },
        "run-review-http": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["run-review"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:url"],
        },
        "run-review-live": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "run-review-style": {
          architectureRole: "application-role",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "web-http": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["run-review-http", "run-review-live", "run-review-style"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:url"],
        },
        "web-server": {
          architectureRole: "application-role",
          allowedModuleDependencies: ["run-review-api", "web-http"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:http", "node:https", "node:url"],
        },
      },
      compositionFiles: {
        "index.js": {
          allowedModuleDependencies: ["application", "run-review", "run-review-api", "run-review-http", "run-review-live", "run-review-style", "web-http", "web-server"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        "main.js": {
          allowedModuleDependencies: ["application", "web-server"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:process"],
        },
      },
    },
    maintenance: {
      architectureRole: "conceptual-package",
      isDeploymentUnit: false,
      path: "packages/maintenance",
      packageName: "@patch-pilot/maintenance",
      sourceRoot: "src",
      allowedWorkspaceDependencies: [],
      modules: {
        approvals: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: ["pg"],
          allowedCoreDependencies: [],
        },
        "change-proposals": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: ["safety"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:path"],
        },
        critiques: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        deliveries: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: ["pg"],
          allowedCoreDependencies: ["node:buffer", "node:crypto", "node:timers", "node:url"],
        },
        "proposal-attempts": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: ["critiques", "verifications"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        runs: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: ["pg"],
          allowedCoreDependencies: [],
        },
        "repository-workspaces": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [
            "node:buffer",
            "node:child_process",
            "node:fs/promises",
            "node:path",
            "node:process",
            "node:url",
            "node:util",
          ],
        },
        "repository-understanding": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: ["safety"],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:fs/promises", "node:path"],
        },
        reproductions: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
        reviews: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: ["pg"],
          allowedCoreDependencies: ["node:crypto"],
        },
        "run-timelines": {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: ["pg", "redis"],
          allowedCoreDependencies: ["node:util"],
        },
        safety: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: ["node:path"],
        },
        verifications: {
          architectureRole: "conceptual-module",
          allowedModuleDependencies: [],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
      },
      compositionFiles: {
        "index.js": {
          allowedModuleDependencies: [
            "approvals",
            "change-proposals",
            "critiques",
            "deliveries",
            "proposal-attempts",
            "repository-understanding",
            "repository-workspaces",
            "reproductions",
            "reviews",
            "runs",
            "run-timelines",
            "safety",
            "verifications",
          ],
          allowedExternalDependencies: [],
          allowedCoreDependencies: [],
        },
      },
    },
  },
};
