import { rm } from "node:fs/promises";
import { basename, resolve, sep } from "node:path";

/**
 * Removes a repository workspace only when it is a generated child of its declared root.
 *
 * @param {{ rootDirectory: string, workspaceDirectory: string }} input Declared root and generated workspace.
 * @returns {Promise<void>}
 * @throws {Error} When the removal target is outside the root or not generated by this module.
 */
export async function removeRepositoryWorkspace(input) {
  const rootDirectory = resolve(input.rootDirectory);
  const workspaceDirectory = resolve(input.workspaceDirectory);
  const hasExpectedParent = workspaceDirectory.startsWith(`${rootDirectory}${sep}`);
  const hasExpectedName = basename(workspaceDirectory).startsWith("repository-");

  if (!hasExpectedParent || !hasExpectedName) {
    throw new Error("Refusing to remove an unrecognized repository workspace.");
  }

  await rm(workspaceDirectory, { force: true, recursive: true });
}
